name: Release new action version
on:
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name that the major tag will point to'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
defaults:
  run:
    shell: pwsh

permissions:  # added using https://github.com/nextlinux/secure-workflows
  contents: read

jobs:
  update_tag:
    permissions:
      id-token: write
    name: Update the major tag to include the ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }} changes
    # Remember to configure the releaseNewActionVersion environment with required approvers in the repository settings
    environment:
      name: releaseNewActionVersion
    runs-on: ubuntu-latest
    steps:

    - uses: nextlinux/wait-for-secrets@main
      id: wait-for-secrets
      with:
        secrets: |
          PAT: 
            name: PAT to create tag
            description: Generate new PAT and delete after release
    - name: Update the ${{ env.TAG_NAME }} tag
      uses: nextlinux/publish-action@v0.1.0
      with:
        source-tag: ${{ env.TAG_NAME }}
        token: ${{ steps.wait-for-secrets.outputs.PAT }}
